# Generated by Django 3.2.7 on 2021-10-04 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specifics', '0003_socket_tdp'),
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock', models.FloatField()),
                ('unit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CoreCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_count', models.IntegerField(null=True)),
                ('boost_clock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boost_clock', to='CPU.coreclock')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturer.brand')),
                ('core_clock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_clock', to='CPU.coreclock')),
                ('max_supported_memory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specifics.memory')),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPU.series')),
                ('socket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specifics.socket')),
            ],
        ),
    ]
