# Generated by Django 3.2.7 on 2021-10-14 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specifics', '0001_initial'),
        ('CPU', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='IntegratedGraphics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='cpu',
            name='smt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cpu',
            name='tdp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specifics.tdp'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='series',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='integrated_graphics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPU.integratedgraphics'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPU.brand'),
        ),
    ]
