# Generated by Django 3.2.7 on 2021-10-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPU', '0002_auto_20211013_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
