# Generated by Django 3.2.7 on 2021-11-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPU', '0003_cpu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
