# Generated by Django 3.2.7 on 2021-10-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifics', '0002_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('unit', models.CharField(max_length=30)),
            ],
        ),
    ]
