# Generated by Django 3.2.7 on 2021-10-04 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specifics', '0001_initial'),
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chipset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CoreClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock', models.FloatField()),
                ('unit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(max_length=30, null=True)),
                ('TDP', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specifics.tdp')),
                ('boost_clock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boost_clock', to='GPU.coreclock')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturer.brand')),
                ('chipset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GPU.chipset')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specifics.color')),
                ('core_clock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_clock', to='GPU.coreclock')),
                ('memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specifics.memory')),
            ],
        ),
    ]
