# Generated by Django 3.2.7 on 2021-10-02 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specifics', '0001_initial'),
        ('GPU', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='memory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='specifics.memory'),
        ),
    ]
