# Generated by Django 3.2.7 on 2021-10-02 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specifics', '0002_color'),
        ('GPU', '0003_alter_gpu_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specifics.color'),
        ),
    ]
