# Generated by Django 3.2.7 on 2021-10-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPU', '0004_gpu_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='TDP',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='length',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
