# Generated by Django 3.2.7 on 2021-10-04 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specifics', '0003_socket_tdp'),
        ('GPU', '0005_auto_20211001_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='TDP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specifics.tdp'),
        ),
    ]
